### ISSUE TITLE
npx can't run the package

### ISSUE THREAD

**Issue by darkmavis1980** [ibbatta/readme-generator#49]
**Describe the bug**
I tried to run the package with npx, but it fails with the error `Cannot read property 'name' of null`

**To Reproduce**

1. Just run `npx readme-generator`

**Expected behavior**
It should start the generator

**Desktop (please complete the following information):**

- OS: Mac OSX Mojave 10.14.6

**Comment by ibbatta** [comment]
Hi @darkmavis1980 , thanks for the issue.
I will check for the error and fix it as soon as possible

**Comment by ibbatta** [comment]
@darkmavis1980 Can you attach here a screen of the error? I cannot reproduce locally.
I've installed the current version 0.1.2 globally (and locally) and when I type `npx readme-generator` on my terminal everything run smooth and fine.

Can you also provide an example of your package.json (or other entry file)?

**Comment by darkmavis1980** [comment]
I just found out what was the issue, I run it in an empty folder thinking that it was going to create the readme, but it clearly need an existing package.json, tried with a folder where I had the package.json and it worked fine, perhaps you can add a check to see if the folder has been initialized by npm or not, just as safety check?

**Comment by ibbatta** [comment]
I will, but it's not that simple: some users have specifically asked to add a cli command to look for another entry file because they would like to use this library even in "non-node" projects. What you are asking me is to look for the existence of a "`package.json`" and, if not found, to ask to specify another entry file, but at the moment it is faster and more practical if the user reads the documentation ( I promise I'll put this feature in a future version!)

Can I close this issue?

**Comment by darkmavis1980** [comment]
Yep, thanks!
